version: "3" # 버전 지정

services: # 컨테이너 설정
  backend:
    container_name: campfood-dev
    image: kimjunseok/campfood-dev
    ports:
      - 8080:8080

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379
