version: "3"

services:
  backend:
    container_name: campfood-dev
    image: kimjunseok/campfood-dev
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/stores:/app/stores

  redis:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379
